# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuredialog.ui'
#
# Created: Tue Jan 21 16:00:39 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 393)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.lineEdit0 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit0)
        self.label1 = QtGui.QLabel(self.configGroupBox)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label1)
        self.UICheckBox = QtGui.QCheckBox(self.configGroupBox)
        self.UICheckBox.setText("")
        self.UICheckBox.setChecked(True)
        self.UICheckBox.setObjectName("UICheckBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.UICheckBox)
        self.label2 = QtGui.QLabel(self.configGroupBox)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label2)
        self.regMethodsComboBox = QtGui.QComboBox(self.configGroupBox)
        self.regMethodsComboBox.setObjectName("regMethodsComboBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.regMethodsComboBox)
        self.label3 = QtGui.QLabel(self.configGroupBox)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label3)
        self.xtolLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.xtolLineEdit.setObjectName("xtolLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.xtolLineEdit)
        self.label4 = QtGui.QLabel(self.configGroupBox)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label4)
        self.sampleLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.sampleLineEdit.setObjectName("sampleLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.sampleLineEdit)
        self.label = QtGui.QLabel(self.configGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.configGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.configGroupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_3)
        self.sLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.sLineEdit.setObjectName("sLineEdit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.sLineEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.configGroupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.txLineEdit.setObjectName("txLineEdit")
        self.horizontalLayout_2.addWidget(self.txLineEdit)
        self.label_5 = QtGui.QLabel(self.configGroupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.tyLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.tyLineEdit.setObjectName("tyLineEdit")
        self.horizontalLayout_2.addWidget(self.tyLineEdit)
        self.label_6 = QtGui.QLabel(self.configGroupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.tzLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.tzLineEdit.setObjectName("tzLineEdit")
        self.horizontalLayout_2.addWidget(self.tzLineEdit)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtGui.QLabel(self.configGroupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.rxLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.rxLineEdit.setObjectName("rxLineEdit")
        self.horizontalLayout_3.addWidget(self.rxLineEdit)
        self.label_8 = QtGui.QLabel(self.configGroupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.ryLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.ryLineEdit.setObjectName("ryLineEdit")
        self.horizontalLayout_3.addWidget(self.ryLineEdit)
        self.label_9 = QtGui.QLabel(self.configGroupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.rzLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.rzLineEdit.setObjectName("rzLineEdit")
        self.horizontalLayout_3.addWidget(self.rzLineEdit)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("Dialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("Dialog", "UI Mode:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("Dialog", "Registration Method:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("Dialog", "Min Relatve Error:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("Dialog", "Points to Sample:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Initial Translation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Initial Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Initial Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))

